# This file was generated by `rails generate rspec:install`.
# It is kept lightweight to ensure fast booting.

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Uncomment the following if you want to use focus:
  # confg.filter_run_when_matching :focus

  # Uncomment to persist example statuses:
  # config.example_status_persistence_file_path = "spec/examples.txt"

  # Uncomment for zero monkey patching mode:
  # config.disable_monkey_patching!

  # Uncomment for verbose output when running a single file:
  # if config.files_to_run.one?
  #   config.default_formatter = "doc"
  # end

  # Uncomment to profile the slowest examples:
  # config.profile_examples = 10

  # Uncomment to run specs in random order:
  # config.order = :random
  # Kernel.srand config.seed
end
